"""
This is a setup.py script generated by py2applet

Usage:
    python setup.py py2app
"""

from setuptools import setup

APP = ['src/ui.py']
DATA_FILES = ['src/main.py', 'icon/']
OPTIONS = {
    'iconfile': "icon/icon.iconset", 
    'plist': {
        'CFBundleName': 'Run Psudocode', 
        'CFBundleDisplayName': 'Run Psudocode', 
        'CFBundleVersion': '1.0.0', 
        'CFBundleIdentifier': 'Run_Psudocode'
    }, 
    'includes': ['os', 'tkinter', '_thread', 'sys']
}

setup(
    app=APP,
    data_files=DATA_FILES,
    options={'py2app': OPTIONS},
    setup_requires=['py2app'],
)
